const http2 = require('http2');

const {
  HTTP_STATUS_OK: STATUS_200_OK,
  HTTP_STATUS_CREATED: CREATED_201,
  HTTP_STATUS_BAD_REQUEST: BAD_REQUEST_400,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: SERVER_ERROR_500,
  HTTP_STATUS_NOT_FOUND: NOT_FOUND_404,
  HTTP_STATUS_FORBIDDEN: FORBIDDEN_ERROR_403,
  HTTP_STATUS_UNAUTHORIZED: UNAUTHORIZED_401,
} = http2.constants;

const patternLink = /^https?:\/\/(?:www\.)?[A-Za-z0-9-._~:/?#[\]@!$&'()*+,;=]+(?:#[A-Za-z0-9-._~:/?#[\]@!$&'()*+,;=]+)?$/m;

module.exports = {
  STATUS_200_OK,
  CREATED_201,
  BAD_REQUEST_400,
  UNAUTHORIZED_401,
  FORBIDDEN_ERROR_403,
  NOT_FOUND_404,
  SERVER_ERROR_500,
  patternLink,
};
